version: "3"

services:
    mysql:
        container_name: "workflow-mysql-${APP_ID}"
        image: "mysql:8.0.19"
        platform: linux/x86_64
        ports:
            - "${MYSQL_PORT}:3306"
        environment:
            TZ: "Asia/Shanghai"
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
        volumes:
            - ./docker/mysql/conf.d:/etc/mysql/conf.d
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/logs:/logs
            - ./docker/mysql/repassword.sh:/etc/mysql/repassword.sh
        command:
            --lower-case-table-names=1
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_general_ci
            --explicit_defaults_for_timestamp=true
        networks:
            network:
                ipv4_address: "${APP_IPPR}.5"
        restart: always

    redis:
        container_name: "workflow-redis-${APP_ID}"
        image: redis
        ports:
            - "${REDIS_PORT}:6379"
        command: "--requirepass ${REDIS_PASS}"
        privileged: true
        environment:
            TZ: "Asia/Shanghai"
        networks:
            network:
                ipv4_address: "${APP_IPPR}.6"
        restart: always
        
networks:
    network:
        name: "workflow-network-${APP_ID}"
        ipam:
            config:
                - subnet: "${APP_IPPR}.0/24"
                  gateway: "${APP_IPPR}.1"